data_ingestion:
  url_download: https://www.kaggle.com/datasets/msambare/fer2013
  data_path: dataset/

data_transformation:
  image_width: 32
  image_height: 32 
  image_channels_expectation: 1
  batch_size: 32

  