data_ingestion:
  url_download: https://www.kaggle.com/datasets/msambare/fer2013/download?datasetVersionNumber=1

data_transformation:
  image_width: 32
  image_height: 32 
  image_channels: 1
  num_classes: 6
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
  random_seed: 242